name: Terraform Plan

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  terraform-plan-nonprod:
    uses: iainazure/devstream_workflows/.github/workflows/terraform_plan.yaml@v0
    with:
      working_directory: infrastructure/environments/nonprod
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_resource_name: devstream_infra
      environment: nonprod
    secrets: inherit
